### ISSUE TITLE
Mongoose DeprecationWarning appears

### ISSUE THREAD

**Issue by engtmk** [shahboura/currency-scraper#12]
got the below warning  and page never get loaded
(node:100071) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

**Comment by shahboura** [comment]
Yes, so far i couldn't remove this warning from console. If you found a fix feel free to make a pull request and i'll merge it back in.

**Comment by shahboura** [comment]
Just noticed  issue title is different than content, for the white page it would remain like this till first scrap is done. Which is at the interval of 15 minutes.
We can remove the interval and invoke the scraping method directly. Is it still not working for you? if not let's open another issue.
I'll update the title accordingly
